{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "durabletask-azurestorage-external-scaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "durabletask-azurestorage-external-scaler.labels" . | nindent 4 }}
rules:
- apiGroups:
  - keda.sh
  resources:
  - scaledobjects
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - deployments/scale
  - scaledsets/scale
  verbs:
  - get
{{- end -}}
