{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "durabletask-azurestorage-external-scaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "durabletask-azurestorage-external-scaler.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "durabletask-azurestorage-external-scaler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "durabletask-azurestorage-external-scaler.fullname" . }}
{{- end -}}
