{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "durabletask-azurestorage-external-scaler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "durabletask-azurestorage-external-scaler.labels" . | nindent 4 }}
{{- end -}}
