name: Scaler Continuous Integration

on:
  push:
    branches: [ main ]
    paths-ignore:
    - README.md

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: ./.github/actions/dotnet-test
        with:
          solution: Scaler
          resultsDirectory: ${{ runner.temp }}/TestResults

      - name: Upload Code Coverage
        uses: ./.github/actions/code-coverage
        with:
          reportPath: ${{ runner.temp }}/TestResults/*/coverage.cobertura.xml

  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish
        uses: ./.github/actions/dotnet-publish
        with:
          project: Keda.Scaler.DurableTask.AzureStorage
          buildConfiguration: Release